### ISSUE TITLE
File not found: pro_ema_inference_epoch138_model.pt

### ISSUE THREAD

**Issue by phupe** [luwei0917/DynamicBind#12]
I am trying to run DynamicBind v1.0 and gets this error message below.

I have installed the wordir directory from zenodo as explained in the README.

How this issue can be solved?

```
Traceback (most recent call last):
  File "/app/dynamicbind/inference.py", line 152, in <module>
    state_dict = torch.load(f'{args.model_dir}/{args.ckpt}', map_location=torch.device('cpu'))
  File "/opt/conda/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/app/dynamicbind/workdir/big_score_model_sanyueqi_with_time/pro_ema_inference_epoch138_model.pt'
inference complete.
0it [00:00, ?it/s]
final step structure relax complete.
(dynamicbind) ls /app/dynamicbind/workdir/big_score_model_sanyueqi_with_time
ema_inference_epoch314_model.pt  model_parameters.yml
```

**Comment by phupe** [comment]
Note that it works if I copy `ema_inference_epoch314_model.pt` into `pro_ema_inference_epoch138_model.pt` but would be better if it could work out-of-the-box without renaming any file.

Thanks.

**Comment by phupe** [comment]
It seems that the `ema_inference_epoch314_model.pt` file is used id the `--paper` option is passed (https://github.com/luwei0917/DynamicBind/blob/main/run_single_protein_inference.py#L123-L125) but this is note the default and this is not documented in the README.

**Comment by phupe** [comment]
This has already been reproted by in https://github.com/luwei0917/DynamicBind/issues/5. I close.
