### ISSUE TITLE
pro_ema_inference_epoch138_model.pt missing

### ISSUE THREAD

**Issue by cjy818github** [luwei0917/DynamicBind#15]
Hi There 

I run into this problem. It seems that pro_ema_inference_epoch138_model.pt is not in the workdir file.

Could you please provide it?

Thanks!

python run_single_protein_inference.py inputs/protein.pdb inputs/ligand.csv --savings_per_complex 40 --inference_steps 20 --header test --device 0 --python /home/jisuan/miniconda3/envs/dynamicbind/bin/python --relax_python /home/jisuan/miniconda3/envs/relax/bin/python
INFO:root:run_single_protein_inference.py inputs/protein.pdb inputs/ligand.csv --savings_per_complex 40 --inference_steps 20 --header test --device 0 --python /home/jisuan/miniconda3/envs/dynamicbind/bin/python --relax_python /home/jisuan/miniconda3/envs/relax/bin/python
2024_03_20_09_59
--------------------------------
Number of complexes:  1
radius protein: mean 71.81570434570312, std 0.0, max 71.81570434570312
radius molecule: mean 11.038935661315918, std 0.0, max 11.038935661315918
distance protein-mol: mean 1.873965516097087e-07, std 0.0, max 1.873965516097087e-07
rmsd matching: mean 0.0, std 0.0, max 0
Traceback (most recent call last):
  File "/home/jisuan/DynamicBind/inference.py", line 152, in <module>
    state_dict = torch.load(f'{args.model_dir}/{args.ckpt}', map_location=torch.device('cpu'))
  File "/home/jisuan/miniconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jisuan/miniconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jisuan/miniconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/jisuan/DynamicBind/workdir/big_score_model_sanyueqi_with_time/pro_ema_inference_epoch138_model.pt'

**Comment by Nobody-Zhang** [comment]
#5
