### ISSUE TITLE
ValueError: Encountered valid chain id that was not present in the LM embeddings

### ISSUE THREAD

**Issue by OlgaKoont** [luwei0917/DynamicBind#41]
Hello, thank you so much for your work!

I ran the script screening.py along with the file ligandFile_with_protein_path.csv through the .sh file:
#!/bin/sh
python screening.py \
--protein_ligand_csv data/8efo_Ki_1000_prot_lig.csv \
--model_dir workdir/big_score_model_sanyueqi_with_time \
--savings_per_complex 40 \
--inference_steps 20 \

Please tell me how I can fix this error: 
parse receptor:   0%|          | 0/1 [00:00<?, ?it/s]
parse receptor:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/tank/scratch/okonovalova/DynamicBind/screening/screening.py", line 138, in <module>
    test_dataset = PDBBindScoring(transform=None, root='', name_list=name_list, protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/mnt/tank/scratch/okonovalova/DynamicBind/screening/datasets/pdbbind.py", line 500, in __init__
    self.ligand_graphs, self.receptor_graphs, self.rdkit_ligands, self.receptor_pdbs = self.inference_preprocessing()
  File "/mnt/tank/scratch/okonovalova/DynamicBind/screening/datasets/pdbbind.py", line 644, in inference_preprocessing
    rec, rec_coords, c_alpha_coords, n_coords, c_coords, chis, chi_masks, lm_embeddings = extract_receptor_structure(copy.deepcopy(rec_model), None, lm_embedding_chains=lm_embeddings_chains_all[i])
  File "/mnt/tank/scratch/okonovalova/DyValueError: Encountered valid chain id that was not present in the LM embeddings
namicBind/screening/datasets/process_mols.py", line 256, in extract_receptor_structure
    raise ValueError('Encountered valid chain id that was not present in the LM embeddings')

Thank you for your help!

**Comment by cureheavy** [comment]
Hi,

Same problem. Have you fixed this problem?

Thank you for your help!
