### ISSUE TITLE
ImportError: DLL load failed while importing rdmolfiles:

### ISSUE THREAD

**Issue by JeongSooNa** [luwei0917/DynamicBind#7]
Hi this is JeongSoo Na

After installation in README file, I try this command

But this error is printed

```
(dynamicbind) PS C:\Users\jsna\Desktop\Github\DynamicBind> python .\run_single_protein_inference.py .\data\1qg8_cleaned.pdb .\data\1qg8_input.csv --savings_per_complex 40 --inference_steps 20 --header test --device $1
Traceback (most recent call last):
  File "C:\Users\jsna\Desktop\Github\DynamicBind\run_single_protein_inference.py", line 10, in <module>
    import rdkit.Chem as Chem
  File "C:\Users\jsna\anaconda3\envs\dynamicbind\lib\site-packages\rdkit\Chem\__init__.py", line 23, in <module>
    from rdkit.Chem.rdmolfiles import *
ImportError: DLL load failed while importing rdmolfiles:
```

How can I run dynamic Bind in window system?
(I also have linux(centOS7, Ubuntu) server too)

**Comment by Nobody-Zhang** [comment]
I don't think it's a good idea to run this file in the system like Windows 10 or so on for the reason that it could be too hard to fix the environment problem just like this... I suggest that you should try running this repo in Ubuntu.
